function skel = include_map_bones_2_width(skel, subject, scale)
    
    names = ["root",...
             "lhipjoint", "lfemur", "ltibia", "lfoot", "ltoes",...
             "rhipjoint", "rfemur", "rtibia", "rfoot", "rtoes",...
             "lowerback", "upperback",...
             "thorax",...
             "lowerneck", "upperneck",...
             "head",...
             "lclavicle", "lhumerus", "lradius", "lwrist",...
             "lhand", "lfingers","lthumb",...
             "rclavicle", "rhumerus", "rradius", "rwrist",...
             "rhand", "rfingers", "rthumb"];

    widths = [  0,...
                0.11,  0.06, 0.045, 0.035, 0.02, ...
                0.11,  0.06, 0.045, 0.035, 0.02, ...
                0.13,  0.15, ...
                0.17, ...
                0.03, 0.04,...
                0.07, ...
                0.05, 0.05, 0.03, 0.03, ...
                0.03, 0.01, 0.01...
                0.05, 0.05, 0.03, 0.03, ...
                0.03, 0.01, 0.01...
             ]; % width in metters

    skel.mapBones2Width = containers.Map(names,widths*scale);
    '';
end